# Generated by Django 6.0.3 on 2026-03-30 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LockerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locatie',
                'verbose_name_plural': 'Locaties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('S', 'Klein'), ('M', 'Medium'), ('L', 'Groot'), ('XL', 'Extra Groot')], default='M', max_length=2)),
                ('status', models.CharField(choices=[('available', 'Beschikbaar'), ('occupied', 'Bezet'), ('maintenance', 'Onderhoud'), ('reserved', 'Gereserveerd')], default='available', max_length=20)),
                ('floor', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='lockers.lockerlocation')),
            ],
            options={
                'verbose_name': 'Locker',
                'verbose_name_plural': 'Lockers',
                'ordering': ['location', 'number'],
                'unique_together': {('location', 'number')},
            },
        ),
    ]
