# Generated by Django 5.0.4 on 2026-03-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
        ('users', '0003_remove_lockeruser_company_lockeruser_website_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='locker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='users.company'),
        ),
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together={('company', 'number')},
        ),
    ]
