# Generated by Django 5.0.4 on 2026-04-02

import django.db.models.deletion
from django.db import migrations, models


def _clone_location_for_company(locker_location_model, source_location, company_id):
    return locker_location_model.objects.create(
        company_id=company_id,
        name=source_location.name,
        address=source_location.address,
        description=source_location.description,
    )


def forwards_move_company_to_location(apps, schema_editor):
    company_model = apps.get_model('users', 'Company')
    locker_location_model = apps.get_model('lockers', 'LockerLocation')
    locker_model = apps.get_model('lockers', 'Locker')
    raspberry_pi_model = apps.get_model('devices', 'RaspberryPi')

    clone_map = {}

    lockers = locker_model.objects.filter(
        location__isnull=False,
        company__isnull=False,
    ).select_related('location')

    for locker in lockers.iterator():
        location = locker.location

        if location.company_id is None:
            location.company_id = locker.company_id
            location.save(update_fields=['company'])
            continue

        if location.company_id == locker.company_id:
            continue

        key = (location.id, locker.company_id)
        new_location_id = clone_map.get(key)
        if new_location_id is None:
            new_location = _clone_location_for_company(locker_location_model, location, locker.company_id)
            new_location_id = new_location.id
            clone_map[key] = new_location_id

        locker.location_id = new_location_id
        locker.save(update_fields=['location'])

    pis = raspberry_pi_model.objects.filter(
        location__isnull=False,
        company__isnull=False,
    ).select_related('location')

    for pi in pis.iterator():
        location = pi.location

        if location.company_id is None:
            location.company_id = pi.company_id
            location.save(update_fields=['company'])
            continue

        if location.company_id == pi.company_id:
            continue

        key = (location.id, pi.company_id)
        new_location_id = clone_map.get(key)
        if new_location_id is None:
            new_location = _clone_location_for_company(locker_location_model, location, pi.company_id)
            new_location_id = new_location.id
            clone_map[key] = new_location_id

        pi.location_id = new_location_id
        pi.save(update_fields=['location'])

    fallback_company_id = company_model.objects.order_by('id').values_list('id', flat=True).first()
    if fallback_company_id is None:
        fallback_company_id = company_model.objects.create(name='Onbekend bedrijf').id

    locker_location_model.objects.filter(company__isnull=True).update(company_id=fallback_company_id)


def backwards_noop(apps, schema_editor):
    # We cannot safely reconstruct locker.company values once removed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_lockeruser_company_lockeruser_website_user'),
        ('lockers', '0002_alter_locker_unique_together_locker_company_and_more'),
        ('devices', '0003_rework_pi_location_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockerlocation',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='locker_locations',
                to='users.company',
            ),
        ),
        migrations.RunPython(forwards_move_company_to_location, backwards_noop),
        migrations.AlterField(
            model_name='lockerlocation',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='locker_locations',
                to='users.company',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='lockerlocation',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='locker',
            name='company',
        ),
        migrations.AlterUniqueTogether(
            name='locker',
            unique_together={('location', 'number')},
        ),
        migrations.AlterModelOptions(
            name='lockerlocation',
            options={
                'ordering': ['company', 'name'],
                'verbose_name': 'Locatie',
                'verbose_name_plural': 'Locaties',
            },
        ),
    ]
