# Generated by Django 5.0.4 on 2026-04-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0004_expand_occupied_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(choices=[('available', 'Beschikbaar'), ('occupied', 'Bezet'), ('maintenance', 'Onderhoud'), ('reserved', 'Gereserveerd')], default='available', max_length=20),
        ),
    ]
