# Generated by Django 5.0.4 on 2026-03-30 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_alter_user_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockeruser',
            name='company',
        ),
        migrations.AddField(
            model_name='lockeruser',
            name='website_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locker_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
