# Generated by Django 5.0.4 on 2026-03-30 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lockers', '0001_initial'),
        ('users', '0002_company_alter_user_options_alter_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actief'), ('ended', 'Beëindigd'), ('cancelled', 'Geannuleerd')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rentals', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='lockers.locker', verbose_name='Locker')),
                ('locker_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='users.lockeruser', verbose_name='Lockergebruiker')),
            ],
            options={
                'verbose_name': 'Huurovereenkomst',
                'verbose_name_plural': 'Huurovereenkomsten',
                'ordering': ['-created_at'],
            },
        ),
    ]
