# Generated by Django 5.0.4 on 2026-04-02

from django.db import migrations, models


def forwards_copy_locker_to_m2m(apps, schema_editor):
    Rental = apps.get_model('rentals', 'Rental')
    through_model = apps.get_model('rentals', 'Rental_lockers')

    through_rows = []
    for rental in Rental.objects.exclude(locker_id__isnull=True).iterator():
        through_rows.append(
            through_model(rental_id=rental.id, locker_id=rental.locker_id)
        )

    if through_rows:
        through_model.objects.bulk_create(through_rows, ignore_conflicts=True)


def backwards_copy_first_locker(apps, schema_editor):
    Rental = apps.get_model('rentals', 'Rental')
    through_model = apps.get_model('rentals', 'Rental_lockers')

    for rental in Rental.objects.iterator():
        first_link = through_model.objects.filter(rental_id=rental.id).order_by('id').first()
        if first_link:
            rental.locker_id = first_link.locker_id
            rental.save(update_fields=['locker'])


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='lockers',
            field=models.ManyToManyField(blank=True, related_name='rentals', to='lockers.locker', verbose_name='Lockers'),
        ),
        migrations.RunPython(forwards_copy_locker_to_m2m, backwards_copy_first_locker),
        migrations.RemoveField(
            model_name='rental',
            name='locker',
        ),
    ]
