# Generated by Django 5.0.4 on 2026-03-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lockers', '0002_alter_locker_unique_together_locker_company_and_more'),
        ('users', '0003_remove_lockeruser_company_lockeruser_website_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryPi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_code', models.CharField(max_length=100, unique=True, verbose_name='Unieke code')),
                ('api_key', models.CharField(editable=False, max_length=255, unique=True, verbose_name='API sleutel')),
                ('location', models.CharField(blank=True, help_text='Fysieke locatie in het bedrijf', max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Fout')], default='offline', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Laatste synchronisatie')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Laatst bekende IP')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspberry_pis', to='users.company')),
            ],
            options={
                'verbose_name': 'Raspberry Pi',
                'verbose_name_plural': "Raspberry Pi's",
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_number', models.IntegerField(verbose_name='Locker-nummer')),
                ('credential_type', models.CharField(choices=[('nfc', 'NFC-tag'), ('pin', 'PIN-code')], max_length=20)),
                ('credential_value', models.CharField(blank=True, max_length=255, verbose_name='Credential')),
                ('status', models.CharField(choices=[('success', 'Succesvol'), ('failed', 'Mislukt'), ('error', 'Fout')], default='failed', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Bericht/Fout')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesynchroniseerd op')),
                ('pi_timestamp', models.DateTimeField(verbose_name='Timestamp Pi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='lockers.locker')),
                ('raspberry_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='devices.raspberrypi')),
            ],
            options={
                'verbose_name': 'Toegangsgebeurtenis',
                'verbose_name_plural': 'Toegangsgebeurtenissen',
                'ordering': ['-pi_timestamp'],
                'indexes': [models.Index(fields=['raspberry_pi', '-pi_timestamp'], name='devices_acc_raspber_72cde6_idx'), models.Index(fields=['locker', '-pi_timestamp'], name='devices_acc_locker__aa35b9_idx'), models.Index(fields=['synced_at'], name='devices_acc_synced__9d4ac4_idx')],
            },
        ),
    ]
