# Generated by Django 5.0.4 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('devices', '0002_alter_accessevent_credential_type'),
        ('lockers', '0002_alter_locker_unique_together_locker_company_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='TRUNCATE TABLE devices_accessevent, devices_raspberrypi RESTART IDENTITY CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='raspberrypi',
            name='location',
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='location',
            field=models.ForeignKey(
                help_text='Locatie waaraan deze Pi gekoppeld is',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='raspberry_pis',
                to='lockers.lockerlocation',
                verbose_name='Locatie',
            ),
        ),
    ]
